# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY server.py ./
# Replace unsupported transport 'shttp' with 'stdio'
RUN sed -i 's/transport=\"shttp\"/transport=\"stdio\"/' server.py

# Start the MCP server via stdio
CMD ["python", "server.py"]
